### ISSUE TITLE
UnhandledPromiseRejectionWarning in github runner container.

### ISSUE THREAD

**Issue by dguiney** [szenius/set-timezone#11]
I get the following error on a github action.

`Run szenius/set-timezone@v1.0
/bin/docker exec  84fb6dea35660f52c06f74[9](https://mycode.dev/org/project/runs/4222125?check_suite_focus=true#step:6:10)77eeb07d6c07b5ebca12[11](https://mycode.dev/org/project/runs/4222125?check_suite_focus=true#step:6:12)3d046a3d932ae5afcaf sh -c "cat /etc/*release | grep ^ID"
Configuring for platform linux
(node:263) UnhandledPromiseRejectionWarning: Error: spawn sudo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:263) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

The only suggestions I can find is to clear cache, but do I really need to do this with a github actions script?

**Comment by szenius** [comment]
Hi @dguiney sorry for the late response. Have you resolved this?
